### ISSUE TITLE
No access possible via URL

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#11]
I try to configure my `Rocket.toml` with the right URL, so I can access the service in my VM via web. I tried:

-  `root = "http://localhost"`
-  `root = "http://10.19.0.2"`
-  `root = "http://10.19.0.2/"`

but nothing works.

Locally on the shell I can access it via http:/localhost:8080

the VM is accessible, i tried a python minimal server which works fine on port 8000

Can you please elaborate, what I have to think about?

**Comment by RalfJung** [comment]
> but nothing works.

What exactly doesn't work? if you can locally access it via http://localhost:8080, the server is running. Everything else is something you need to set up in your VM software. You probably need to set up port forwarding or something like that.

**Comment by rubo77** [comment]
So how so I have to change this if I don't want to use a proxy?


    root = "https://..."

In my case the VM only serves this service.

**Comment by RalfJung** [comment]
The `root` has nothing to do with it. That's just the URL that it will be put in the emails.

You have to change the `address`. Try
```
address = "0.0.0.0"
```

**Comment by rubo77** [comment]
> You have to change the address. Try
>
>        address = "0.0.0.0"
>
>That should make it listen on all addresses.

That worked. You should add this in the Readme too, or set this as default in Rocket.toml.dist

**Comment by RalfJung** [comment]
The README is written assuming you will configure a reverse proxy. In that case, you do *not* want to set the address to `"0.0.0.0"`. Hence it's not going to become the default.

I may mention it in the `Rocket.toml.dist`, though.
