### ISSUE TITLE
possibility to use external stylesheet

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#17]
We use a CMS for our Freifunk page. There we could generate a file that could work as template for the ff node motor.

Or do you know a better solution to include the monitor pages into an existing website?

An Iframe would work quite bad, because the monitor pages would come from a different domain or port than the homepage... Hmm ... Maybe if the monitor pages are served in a subfolder.. 

If that works, please hint to a working solution in the readme

**Comment by RalfJung** [comment]
I don't know what you mean by "generate a file that could work as template". This sounds like something that you have to figure out with your CMS, I don't think I can help much.

However, I can provide an option that lets you give a URL to a stylesheet that is added to all pages. You are making that request in the issue title but do not mention it in the actual description. Would that help?

**Comment by rubo77** [comment]
I will try tomorrow with the current state.

Maybe I find a solution already

**Comment by RalfJung** [comment]
Fixed by 87da395a7882d5f0a0b19c38cea0aa38577e6612
