### ISSUE TITLE
error Handling

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#2]
If you don't enter a valid email, there is no error message

**Comment by RalfJung** [comment]
Well, I am getting a "500 internal server error". That's an error message, but not a good one I agree :)

**Comment by rubo77** [comment]
In the first step, you just get the second selection page without error. If you select a node then, then you get the 500 error

**Comment by RalfJung** [comment]
Fixed by 538b90af545bba9e76a1d54f2f64e52a0c038e5e
