### ISSUE TITLE
Change license to be less restictive

### ISSUE THREAD

**Issue by MoritzFago** [freifunk-saar/ff-node-monitor#21]
The AGPL considers network use distribution. This means that every visitor of the website is entitled to a copy of the source. This (theoretically) means a big administrative overhead. I'd like to suggest to use the standart GPL (v2) and putting a link to this repository on the user interface. This would serve the same purpose, but wouldn't be legally binding, so the user would have to go to get the source, not us providing it.

**Comment by BenBE** [comment]
Use of the AGPL for networked software is the exact use case for which it was created.

Also note that the GPLv3 fixes several issues the GPLv2 had, regarding protection of user rights by avoiding TiVoization and related issues.

Thus essentially the AGPL ensures every user is granted the right to access its source code, which can be implemented with as little as a link to some code repository. Reducing this privilege using the GPLv2 to only people running the software would be kinda opposite from what intention of the GPLv2 would normally grant.

Furthermore: Having a link to the source repository is practically providing the source, as the AGPL doesn't enforce any specific medium of transfer. Thus I don't see the problem with the mentioned administrative overhead, apart from writing a patch to include this link into the user interface - which surely is more than welcome for this project.

**Comment by RalfJung** [comment]
> Use of the AGPL for networked software is the exact use case for which it was created.

Exactly. I made this choice deliberately. The license is not going to change.

> writing a patch to include this link into the user interface - which surely is more than welcome for this project.

Good point, I should've done this from the beginning.

**Comment by RalfJung** [comment]
I added a link in 478c608d7cdbb0364e5459d6eff5c499ca0d6d25
