### ISSUE TITLE
How do I have to configure mail on my server?

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#22]
I got the service running on my server: https://freifunk.in-kiel.de/knotenalarm/

But email is not working.

How do I  [Make sure you have a mail service running locally that is set up to deliver emails from that address?](https://github.com/freifunk-saar/ff-node-monitor/blob/master/Rocket.toml.dist#L4)

What packages and tools do I have to install on the server? Maybe you can add this to the Vagrant bootstrap file?

[Here I described, how my server is setup](https://unix.stackexchange.com/questions/450735/send-mails-from-one-vm-when-postfix-is-on-the-other-vm-in-the-same-server)

**Comment by RalfJung** [comment]
Uh, setting up email is highly context-dependent. Essentially you should make sure that `mail` works reasonably on that system. Depending on whether this is a public-facing system with a static IP and hostname, this can mean directly delivering email or relaying it via another host.

I think describing mail server setup is way out of scope for this application. I personally can recommend postfix, and you'll find tons of tutorials for how to configure it for direct or indirect (relay/"satellite system") delivery. [This looks like a good start](http://www.postfix.org/BASIC_CONFIGURATION_README.html).

**Comment by RalfJung** [comment]
In your three-VM setup, is there an internal ("behind the NAT") network which the VMs can use to talk to each other? I think I can make the host that email is submitted to configurable, so it would be localhost per default but you could set it to your email VM. Then you'd just have to configure postfix in that VM to accept emails from the services VM for relay.

**Comment by rubo77** [comment]
>I think I can make the host that email is submitted to configurable

that  would be great

**Comment by rubo77** [comment]
Or could you add email config settings, where you can enter 

- hostname
- username
- password
- ...

all settings, you need to log in into any email account and send it over that account

**Comment by rubo77** [comment]
I got an answer on https://unix.stackexchange.com/a/450745/20661

**Comment by RalfJung** [comment]
> Or could you add email config settings, where you can enter

I'll leave that to someone else to implement. ;)
Servers should have working email anyway to the admin can be informed about cron failure and similar.

**Comment by RalfJung** [comment]
Fixed by 8f45ded02c06f091938cf50b444d01f3fcb2062b.
