### ISSUE TITLE
Umlaut kaputt?

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#24]
https://github.com/freifunk-saar/ff-node-monitor/blob/b4d0ba8b9a5e25352c6988a9d932fb908d67ce60/templates/index.html.hbs#L19

An dieser stelle habe ich ein anderes ü als weiter unten.

ich musste dies aendern, damit die email keinen umlautfehler dort anzeigt:
```
-  {{config.ui.instance_name}} Knoten<C3><BC>berwachung
+  {{config.ui.instance_name}} Knoten<C3>berwachung
```````````````

**Comment by rubo77** [comment]
aber selbst dann ist im mail header das ü kaputt:

    From: "Freifunk Kiel KnotenÃ¼berwachung" <absender@mail.hier>

**Comment by RalfJung** [comment]
Welches E-Mail-Setup verwendest du? Ich habe einen Postfix mail server und Thunderbird als client; da sehen alle Umlaute aus wie sie sollen.

> `+  {{config.ui.instance_name}} Knoten<C3>berwachung`

Das sieht falsch aus; in UTF-8 hat das "ü" zwei Byte. Und wo ist `C3`  ein "ü"?

> `KnotenÃ¼berwachung`

Das sieht so aus, als würde ein UTF-8-Text als ISO-8859-1 interpretiert -- warum auch immer.

**Comment by rubo77** [comment]
Ja, stimmtm die stelle hat den fehler bei mir doch nicht behoben.

Ich benutze Thunderbird, dort sieht der quelltext der email so aus:

> Received: from freifunk (unknown [10.77.77.102])
> 	by meinserver.de (Postfix) with ESMTP id 0210F1242BBC
> 	for <meine@email>; Sat,  7 Jul 2018 22:09:08 +0200 (CEST)
> Subject: Freifunk Kiel KnotenÃ¼berwachung: Ãœberwachung von 84:16:f9:9b:e4:12
> To: <meine@email>
> From: 
> 	"Freifunk Kiel KnotenÃ¼berwachung" <absende@email.aus.Rocket.toml>

diue Üs im subject zeigt mein Thunderbird dann richtig an, aber das in dem From zeigt thunderbird im Email titel richtig, aber in der email-Liste falsch an.

wo wird denn das wort "Knotenüberwachung" definiert? ich würde das sowieso gerne ändern können.

**Comment by rubo77** [comment]
Mach doch alle Texte in ein translations file

**Comment by RalfJung** [comment]
Das würde das Problem nicht lösen -- die meisten würde man ja als Sysadmin nicht anpassen wollen.

**Comment by RalfJung** [comment]
Upstream bug: https://github.com/lettre/lettre/issues/304

**Comment by rubo77** [comment]
Seit dem letzten Update kann man in der Rocket.toml jetzt einen Namen ohne Umlaute definieren, wodurch die Mails auch wieder ok aussehen. z.b. "Knotenalarm"

Leider wird dieser Name noch nicht in der Überschrift der Knotenüberwachung benutzt.

**Comment by rubo77** [comment]
Mein Fehler. Ich dachte bei der Bestätigung Knotenüberwachung, dass die Überschrift alt wäre

**Comment by RalfJung** [comment]
Current status: There is https://github.com/niax/rust-email/pull/44 but it needs more work.

**Comment by RalfJung** [comment]
Fixes by e5f4d4b2d2f175b6cdff00ed9613f1cb4938fd89
