### ISSUE TITLE
node-ids with colon are not working

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#27]
if you enter a node id with colons like 84:16:f9:9b:e4:12 the nodewatch cannot be activated:

     84:16:f9:9b:e4:12 wurde schon von my@mail überwacht, oder es gibt keinen Knoten mit dieser ID. 

the colons should be remmmoved on sending and also **trimmed**, in case there are some **space** before or after left

**Comment by RalfJung** [comment]
I disagree. The node ID is a concept external to the node monitor, handled by gluon and hopglass. I don't want to make assumptions like it not containing a colon.

I'd be fine having a more clever selection box for "select by name" though where one can filter, and where entering the MAC also does the right thing for filtering. That needs HTML/JS magic way beyond my level, though.

**Comment by rubo77** [comment]
But the warning, that the node with colons dowsn't exist could pre-pone a check if the node without colons exists and if so then takeeeee that one intelligently.

**Comment by rubo77** [comment]
> does the right thing for filtering. That needs HTML/JS magic way beyond my level, though.

You can use one of the examples  in the answers here: https://stackoverflow.com/questions/9206013/javascript-fuzzy-search#15252131

**Comment by RalfJung** [comment]
> But the warning, that the node with colons dowsn't exist could pre-pone a check if the node without colons exists and if so then takeeeee that one intelligently.

I don't like such ad-hoc hacks. Node ID and Node MAC are just two distinct concepts.

> You can use one of the examples in the answers here: https://stackoverflow.com/questions/9206013/javascript-fuzzy-search#15252131

That's just the half that does the filtering, the bigger problem is how to even create a "filterable dropdown" UI. The things I found when doing a bit of research into this all either looked horrible in the UI or required enormous amounts of JS code which I did not want to deal with.

**Comment by rubo77** [comment]
the code looks fine, do you have it in action already somewhere?

**Comment by rubo77** [comment]
Great! perfect! ;)

But is the first input field needed now? If I try to add a node that does not exist in the list, I get this error: 

> Es ist ein Fehler aufgetreten: Der angegebene Knoten aaaaaaaaaaaa existiert nicht und kann daher nicht überwacht werden.

Either the first field should accept node ids, that are not in that list, or it can be dropped completely.

**Comment by RalfJung** [comment]
> But is the first input field needed now?

Good point! I removed it.
