### ISSUE TITLE
Sort nodes in selectbox case insensitive

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#28]
If there are a few hundred nodes it is easy to jump to the first letter by typing innnn the selectbox. But if some nodes are capitalized some small, the capital letters are at the front at the moment. this is not very handy

**Comment by RalfJung** [comment]
Actually what I'd really like to see is the possibility to enter arbitrary text and have the entries in the select box filtered appropriately. That requires some serous HTML/JS magic, though.

**Comment by rubo77** [comment]
see here: https://stackoverflow.com/questions/9206013/javascript-fuzzy-search#15252131

**Comment by RalfJung** [comment]
Actually nodes *are* sorted case-insensitive for me:
```
<option value="f81a6741f325">ffsaar_gard-freifunk-re-04 (f81a6741f325)</option>
<option value="98ded0d612ec">ffsaar-GasthausReichert (98ded0d612ec)</option>
<option value="98ded0d60268">ffsaar-GasthausReichert-Repeater (98ded0d60268)</option>
<option value="60e327fb45b5">ffsaar-gde-kohn (60e327fb45b5)</option>
<option value="60e327cf358a">ffsaar-gde-kohn-2 (60e327cf358a)</option>
<option value="f4f26d3eaf42">ffsaar-Geisbachhalle-Fremersdorf (f4f26d3eaf42)</option>
 ```
Are they not for you?

**Comment by rubo77** [comment]
not at my instance: https://freifunk.in-kiel.de/knotenalarm/list?email=test@test.de

**Comment by rubo77** [comment]
```

 lc_collate 
------------
 C
(1 row)

```

**Comment by RalfJung** [comment]
Yeah that doesn't look right. I guess I should set the collation explicitly in the DB migrations.

**Comment by rubo77** [comment]
yes, you should.

I found in my setup, that locales was set to `none` which is C

I called this now:

    dpkg-reconfigure locales

and set the global locales to de utf8

But this will not change existing databases.

seems I have to dump and reimport the database, see https://stackoverflow.com/questions/5090858/how-do-you-change-the-character-encoding-of-a-postgres-database

But maybe there is a solution to set the ordering in the sql command too?

**Comment by RalfJung** [comment]
Turns out I cannot set the collation in DB migrations -- as you also found out, the collation cannot be changed once the DB has been created. Also, the default collation is picked by PostgreSQL dependong on the system, it seems, and you didn't set up a unicode-aware locale in your system.

I have changed the README instructions to set the collate explicitly when creating the DB, to avoid depending on the system locale. Unfortunately, there is not much I can do for your setup. I'm afraid you will have to export and reimport.

> But maybe there is a solution to set the ordering in the sql command too?

I didn't find anything like that. Also, that would be carrying a work-around indefinitely for a single setup that accidentally used the wrong locale -- I don't think that's a good trade-off, I am afraid.

**Comment by rubo77** [comment]
I need to dump with

    sudo -u postgres pg_dump ff-node-monitor > /tmp/backup.sql
then delete and recreate with something like

    pg_restore  -U me -d mydatabase -W /tmp/backup.sql

?

**Comment by RalfJung** [comment]
That looks reasonable. I did not try though.

You could try restoring to another DB. So, create a `ff-node-monitor-2` (using the command in the README), import into that and use that for the node monitor -- then you don't have to delete anything.
Only when everything works using `ff-node-monitor-2`, delete the old DB.

**Comment by rubo77** [comment]
```
sudo -u postgres pg_dump ff-node-monitor > /tmp/ff-node-monitor.sql
sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor2" WITH OWNER = "ff-node-monitor" LC_COLLATE = '\''de_DE.utf8'\'' TEMPLATE template0;'        
sudo -u postgres psql -d ff-node-monitor2 -1 -f /tmp/ff-node-monitor.sql

$ sudo -u postgres psql ff-node-monitor2 -c "SHOW LC_COLLATE"   
 lc_collate                                                                       
------------                                                                      
 de_DE.utf8                                                                       
(1 Zeile)                                                                         
                                                                                  
```
