### ISSUE TITLE
unknown locale de_DE

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#36]
in my english vagrant box, i get the error

    $ sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor" WITH OWNER = "ff-node-monitor" LC_COLLATE = "de_DE.UTF-8 UTF-8" TEMPLATE template0;'
    ERROR:  invalid locale name: "de_DE.UTF-8 UTF-8"

Do I have to activate the new locales in postgresql somehow?

it is installed:
```

# echo $LANG
de_DE.UTF-8

```

**Comment by RalfJung** [comment]
You used `en_US.UTF-8` now? That probably also works though I did not try.

It is possible that you have to install the German locale before postgres can use it. On Debian, youÄd do that via `sudo dpkg-reconfigure locales`.

**Comment by rubo77** [comment]
I did all that and tried both de and us, but on my server it does this error:

```
sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = "de_DE.UTF-8" TEMPLATE template0;'
ERROR:  syntax error at or near ""de_DE.UTF-8""
LINE 1: ...tor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = "de_DE.UTF...
```

**Comment by RalfJung** [comment]
Do you have the de_DE locale installed? `locale -a` should tell you.

**Comment by rubo77** [comment]
```

root@freifunk:/tmp# locale -a|grep de_DE
de_DE
de_DE@euro
de_DE.utf8
root@freifunk:/tmp# locale -a|grep en_US
en_US
en_US.iso885915
en_US.utf8

```

**Comment by rubo77** [comment]
in vagrant I found out, that you need ` locales-all` being installed (#37).

But on my debian 8.1 server i have no solution jet

**Comment by RalfJung** [comment]
`locales-all` is a HUGE waste of space:
```
Installed-Size: 136 MB
```

**Comment by rubo77** [comment]
On my problematic debian 8.1 I have 

    psql (PostgreSQL) 9.4.18   

in my vagrant stretch box, where the same command works, i have

    psql (PostgreSQL) 9.6.7                 

I tried again the command in vagrant:

    # sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = "de_DE.UTF-8" TEMPLATE template0;'                                                                                                    
    CREATE DATABASE

**Comment by RalfJung** [comment]
The error also doesn't look like the problem is a missing locale:
```
syntax error at or near ""de_DE.UTF-8""
```
Maybe try using `'` instead of `"` as quotes around `de_DE.UTF-8`?

**Comment by RalfJung** [comment]
So the shell command would be something like
```
sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = '\''de_DE.UTF-8'\'' TEMPLATE template0;'
```

**Comment by rubo77** [comment]
No change

**Comment by RalfJung** [comment]
What if you try `de_DE.utf8` instead?
```
sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = "de_DE.utf8" TEMPLATE template0;'
```
or
```
sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = '\''de_DE.utf8'\'' TEMPLATE template0;'
```

**Comment by rubo77** [comment]
you are brilliant! this works:

    sudo -u postgres psql -c 'CREATE DATABASE "ff-node-monitor3" WITH OWNER = "ff-node-monitor" LC_COLLATE = '\''de_DE.utf8'\'' TEMPLATE template0;'

this looks fine:

```
# sudo -u postgres psql ff-node-monitor3 -c "SHOW LC_COLLATE"                                                                                                                               
 lc_collate                                                                                                                                                                                                   
 de_DE.utf8                                                                                                                                                                                                   
```

**Comment by RalfJung** [comment]
Glad this worked :)

> Do you add this to the readme then?

Done.

**Comment by rubo77** [comment]
how did you find out that it is needed the single quote `'\''`?

**Comment by RalfJung** [comment]
I googled around and saw single quotes used for other strings in `CREATE DATABASE` (namely, the `ENCODING`) so I figured it might work here, too... So, really, I guessed^^
