### ISSUE TITLE
cron not working

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#40]
Here I get an internal server error: https://freifunk.in-kiel.de/knotenalarm/cron

how can I debug this?

in Rocket.toml I have this nodelist configured: https://hopglass.freifunk.in-kiel.de/nodes.json

**Comment by RalfJung** [comment]
> how can I debug this?

Look at the systemd journal on the server. There should be a panic message with some details in the logs. (It's printed to stderr.)

**Comment by rubo77** [comment]
```
Jul 26 00:00:02 freifunk ff-node-monitor[27932]: Error: Response was a non-`Responder` `Err`: Error("missing field `node_id`", line: 1, column: 405944).
Jul 26 00:00:02 freifunk ff-node-monitor[27932]: Warning: Responding with 500 Internal Server Error catcher.
Jul 26 00:00:02 freifunk sSMTP[16346]: Sent mail for ... (221 2.0.0 Bye) uid=119 username=ff-node-monitor outbytes=1522
Jul 26 00:00:02 freifunk CRON[16275]: pam_unix(cron:session): session closed for user ff-node-monitor
Jul 26 00:10:01 freifunk CRON[17862]: pam_unix(cron:session): session opened for user ff-node-monitor by (uid=0)
Jul 26 00:10:01 freifunk CRON[17865]: (ff-node-monitor) CMD (curl http://localhost:8833/cron)
Jul 26 00:10:02 freifunk ff-node-monitor[27932]: Error: Response was a non-`Responder` `Err`: Error("missing field `node_id`", line: 1, column: 405797).
Jul 26 00:10:02 freifunk ff-node-monitor[27932]: Warning: Responding with 500 Internal Server Error catcher.
Jul 26 00:10:02 freifunk sSMTP[17911]: Sent mail for ... (221 2.0.0 Bye) uid=119 username=ff-node-monitor outbytes=1522
Jul 26 00:10:02 freifunk CRON[17862]: pam_unix(cron:session): session closed for user ff-node-monitor
```

**Comment by rubo77** [comment]
at first I thought, there is missing a node_id in the json file, but there are as many node_ids as hostnames in nodes.json:

```
$ cat nodes.json|jq '.["nodes"][]["nodeinfo"]'|grep -E "hostname" |wc -l
416
ruben@zyklopenhaufen:/tmp$ cat nodes.json|jq '.["nodes"][]["nodeinfo"]'|grep -E "node_id" |wc -l
416
````

**Comment by RalfJung** [comment]
Yes but this does mean that the field is missing. 405k characters into the stream. Is there a good way to look at that?^^

What is the URL for the node JSON file?

**Comment by rubo77** [comment]
> in Rocket.toml I have this nodelist configured: https://hopglass.freifunk.in-kiel.de/nodes.json

**Comment by RalfJung** [comment]
`curl https://hopglass.freifunk.in-kiel.de/nodes.json| jq '.nodes[].nodeinfo.node_id?'` shows that you do have a node with no ID.

The JSON looks like this
``
    {
      "nodeinfo": {},
      "flags": {
        "online": false
      },
      "statistics": {},
      "lastseen": "2018-07-16T05:52:01.860Z",
      "firstseen": "2018-07-15T08:19:24.590Z"
    },
```
That looks bogus to me?

**Comment by rubo77** [comment]
could you filter those bogus entries out?

**Comment by RalfJung** [comment]
Well I can declare node_id and hostname optional fields I guess. Will complicate the logic but well...

**Comment by RalfJung** [comment]
Fixed by 70c328336400126f4c42c6a4db308d68d9e1d30a

**Comment by rubo77** [comment]
thanks, works! no  internal server error any more

maybe you could be a bit more verbose on the error messages on the generated webpage for future debugging?

**Comment by RalfJung** [comment]
I don't think that would be a good idea. Error messages are something atackers love to target to squeeze information out of the system.

This is exactly what the error log is for. The error message in the log could be more informative, maybe -- but the web interface shouldn't say anything.

**Comment by RalfJung** [comment]
Yes. That's general systemd stuff but it might still be helpful.
