### ISSUE TITLE
no database after restart

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#43]
I rebooted the server and now get this error:

`panicked at 'failed to connect to db: BadConnection("could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n")', libcore/result.rs:945:5
`

**Comment by rubo77** [comment]
fixed with

    /etc/init.d/postgresql restart
    sudo systemctl start ff-node-monitor

Not sure, if we have to do something about this problem?

**Comment by rubo77** [comment]
this seems a problem: after a restart the postgreql service is in a state, where it is not serving the satabase properly. A `service postgresql restart` fixes this.

How can we ensure, that postgresql is running properly? or maybe wait a bit longer before the node-watcher starts?

**Comment by RalfJung** [comment]
FWIW, I have not had this problem on our server.

Our systemd file declares the correct dependencies:
```
Requires=postgresql.service
After=postgresql.service
```
So this is a bug in postgres -- its systemd file needs to guarantee that the connection is available when the state transitions to "ready".
