### ISSUE TITLE
Readme: add info which folders can be deleted after install

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#49]
there are ~1.5GB of space used during install

please add info which folders can be deleted without problem. Or add instructions how to build locally and deploy only the needed files to a production server

**Comment by rubo77** [comment]
please add info, what I can remove, I think I don't need 1.5GB on my server if I do not rebuild the project every day

**Comment by RalfJung** [comment]
I haven't had time to do this research yet. But why don't you just do it yourself? Delete some stuff, restart the service and see if it comes back up. It's not hard, and you don't have to wait for me to figure everything out for you...

`targets/release` contains the binary, as you can see from your systemd service file. Obviously you cannot delete the binary. :)  But you should be able to delete everything else in there.

**Comment by rubo77** [comment]
You can remove those files:

    rm -rf  /opt/ff-node-monitor/.rustup  \
      /opt/ff-node-monitor/src/target/release/deps  \
      /opt/ff-node-monitor/src/target/release/build

**Comment by RalfJung** [comment]
Thanks!

However, this way you will have to install Rust again next time (it is installed into `.rustup`). So I think the README should only recommend to delete `target/*/{deps,build}`.

**Comment by rubo77** [comment]
I don't think `.rustup` is needed any more, I just updated my ff-node-monitor and it works fine

**Comment by RalfJung** [comment]
`.rustup` contains `cargo` and `rustc` and the entire Rust installation. After deleting it, you cannot even do `cargo build` any more.

**Comment by rubo77** [comment]
ah right, I looked in src/.rustup

so this is recreated but it only takes some few seconds to recreate that one, so I think it can be recommended to be deleted too (700MB)

**Comment by RalfJung** [comment]
Also see 388283566f9ab5167d3fd301c30cded06ddd282b
