### ISSUE TITLE
compiling with  older nightly

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#5]
Due to the currently broken Rocket (see https://github.com/freifunk-saar/ff-node-monitor/issues/3#issuecomment-396517085), I used an  older nightly:

    $ sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustup default nightly-2018-06-09

But then I get an this error:

```
   Compiling email v0.0.19
error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied
  --> /var/lib/ff-node-monitor/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Add` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable
```

**Comment by RalfJung** [comment]
That is strange. Which exact commit of ff-node-monitor is that? What does `rustc --version` say? (Or rather, `sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustc --version`.)

We have a [green CI build](https://travis-ci.org/freifunk-saar/ff-node-monitor/builds/390342352) for that nightly.

**Comment by rubo77** [comment]
sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustc --version
    rustc 1.28.0-nightly (8afb89493 2018-06-08)

**Comment by rubo77** [comment]
in your commit history the ci fails too with a red X:
https://github.com/freifunk-saar/ff-node-monitor/commits/master

**Comment by RalfJung** [comment]
Yes, that's the later build with newer nightlies. I linked to the one that worked.

It seems you got the `2018-06-08` nightly though you asked for `2018-06-09`. Maybe try 
```
sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustup default nightly-2018-06-10
```

**Comment by rubo77** [comment]
I added that in my bootstrap for varant:

https://github.com/rubo77/ff-node-monitor/tree/vagrant/vagrant

it is building now .....

**Comment by RalfJung** [comment]
The fix has been merged in Rust, so I think today's or tomorrow's nightly will work again. I don't think it makes sense to update the README for that.

What would make sense is to find some way to avoid repeating this whenever Rocket breaks on Rust nightly -- which will happen again. I guess I'll open an issue to track ideas for that, though I don't have any good ideas.
