### ISSUE TITLE
vagrant-box: Upgrade to Debian buster

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#60]
I try to get it runniing on debian 10 in the vagrant-box:
https://github.com/rubo77/ff-node-monitor/commits/buster

but it crashes at install of ssmtp, which seems not to be available any more:

https://unix.stackexchange.com/questions/525235/install-ssmtp-in-debian-buster

**Comment by RalfJung** [comment]
Hm, that's annoying. On any "real" system you'd probably want to use postfix or so anyway but that seems a bit heavy-weight for a vagrant box. You know vagrant better than I do, what do people usually do when they need email in their box?

**Comment by rubo77** [comment]
They suggested msmtp in https://unix.stackexchange.com/questions/525235/install-ssmtp-in-debian-buster

I rebuild the vagrant buster box again without ssmtp package and it starts fine so far.
What exacty was the ssmtp in the box for? what kind of emails are send where?

**Comment by RalfJung** [comment]
> What exacty was the ssmtp in the box for? what kind of emails are send where?

This is for the emails you get when adding/removing a node, to confirm that the owner of that email address really wants to watch / stop watching those nodes.
