### ISSUE TITLE
Don't send warnings if ALL nodes are offline

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#66]
We sometimes have problems with our map. Then all nodes are shown as offline. In such case, the monitor shouldn't send out warning emails.

seems trivial, I would add something like

    if numnodes <10 then dontsend emails

Where would be the place in the code, I have to look for to add such a change?

**Comment by RalfJung** [comment]
This should be configurable and off-by-default; I wouldn't want to hie warnings in the default configuration.

The code that detects state changes in the nodes is here:

https://github.com/freifunk-saar/ff-node-monitor/blob/4342463a9c25c7d9f126cf0f42e10c364ee387dd/src/cron.rs#L137-L166
