### ISSUE TITLE
error: component 'rustfmt'

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#74]
I got this today when upgrading to the latest master commit:

    error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly-2020-06-20

**Comment by rubo77** [comment]
everything seems to work fine though after the upgrade. ;/

**Comment by RalfJung** [comment]
Yeah latest nightly doesn't have rustfmt. That happens.^^ I don't think there's a bug here though.
